<?php
declare(strict_types=1);
require_once 'config/database.php';require_once 'config/config.php';require_once 'includes/functions.php';
$slug=trim($_GET['slug']??'');$s=$pdo->prepare("SELECT id,name,slug,description,image FROM categories WHERE slug=:slug AND status='active' LIMIT 1");$s->execute([':slug'=>$slug]);$category=$s->fetch(PDO::FETCH_ASSOC);
if(!$category){http_response_code(404);$pageTitle='Category Not Found';$activePage='';require 'includes/store-header.php';echo '<section class="section"><div class="container empty-state"><h2>Category not found</h2><p>The category you requested is not available.</p><a class="btn-primary" href="'.BASE_URL.'shop.php">Back to Shop</a></div></section>';require 'includes/store-footer.php';exit;}
$pageTitle=$category['name'];$activePage=$category['slug'];
$s=$pdo->prepare("SELECT p.id,p.name,p.slug,p.image,MIN(CASE WHEN pv.status='active' AND pv.quantity>0 AND p.stock>=pv.quantity THEN p.price*pv.quantity END) AS starting_price,COUNT(CASE WHEN pv.status='active' THEN 1 END) AS pack_count FROM products p LEFT JOIN product_variants pv ON pv.product_id=p.id WHERE p.category_id=:category_id AND p.status='active' GROUP BY p.id,p.name,p.slug,p.image HAVING starting_price IS NOT NULL ORDER BY p.featured DESC,p.created_at DESC");$s->execute([':category_id'=>$category['id']]);$products=$s->fetchAll(PDO::FETCH_ASSOC);
?>
<?php require 'includes/store-header.php';?>
<section class="page-hero"><div class="container"><h1><?=e($category['name'])?></h1><div class="breadcrumb"><a href="<?=BASE_URL?>index.php">Home</a> / <?=e($category['name'])?></div><?php if($category['description']):?><p class="breadcrumb" style="max-width:650px;font-size:13px;"><?=e($category['description'])?></p><?php endif;?></div></section>
<section class="section"><div class="container"><div class="listing-top"><p><?=count($products)?> product<?=count($products)!==1?'s':''?> available</p><a class="view-all" href="<?=BASE_URL?>shop.php">View all →</a></div><?php if($products):?><div class="product-grid"><?php foreach($products as $p):?><article class="product-card"><a class="product-image" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>"><?php if($p['image']):?><img src="<?=BASE_URL.ltrim($p['image'],'/')?>" alt="<?=e($p['name'])?>"><?php else:?><div class="product-placeholder">✦</div><?php endif;?></a><div class="product-body"><div class="product-category"><?=e($category['name'])?></div><a class="product-name" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>"><?=e($p['name'])?></a><div class="product-price">From ₹<?=number_format((float)$p['starting_price'],2)?></div><div class="product-footer"><span class="product-unit"><?=number_format((int)$p['pack_count'])?> pack option<?=((int)$p['pack_count'])!==1?'s':''?></span><a class="add-btn" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>">View</a></div></div></article><?php endforeach;?></div><?php else:?><div class="empty-state"><h2>No products available</h2><p>There are currently no products available in this category.</p></div><?php endif;?></div></section>
<?php require 'includes/store-footer.php';?>
