<?php
declare(strict_types=1);
require_once 'config/database.php';require_once 'config/config.php';require_once 'includes/functions.php';
$pageTitle='Shop';$activePage='';
$categories=$pdo->query("SELECT id,name,slug FROM categories WHERE status='active' ORDER BY display_order ASC,name ASC")->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->query("SELECT p.id,p.name,p.slug,p.image,c.name AS category_name,c.slug AS category_slug,MIN(CASE WHEN pv.status='active' AND pv.quantity>0 AND p.stock>=pv.quantity THEN p.price*pv.quantity END) AS starting_price,COUNT(CASE WHEN pv.status='active' THEN 1 END) AS pack_count FROM products p INNER JOIN categories c ON c.id=p.category_id AND c.status='active' LEFT JOIN product_variants pv ON pv.product_id=p.id WHERE p.status='active' GROUP BY p.id,p.name,p.slug,p.image,c.name,c.slug HAVING starting_price IS NOT NULL ORDER BY p.featured DESC,p.created_at DESC");
$products=$stmt->fetchAll(PDO::FETCH_ASSOC);function shopImageUrl(?string $p):?string{return $p?BASE_URL.ltrim($p,'/'):null;}
?>
<?php require 'includes/store-header.php';?>
<section class="page-hero"><div class="container"><h1>Shop Fresh</h1><div class="breadcrumb">Home / Shop</div></div></section>
<section class="section"><div class="container"><div class="listing-layout"><aside class="filter-card"><h3>Categories</h3><a class="active" href="<?=BASE_URL?>shop.php">All Products</a><?php foreach($categories as $c):?><a href="<?=BASE_URL?>category.php?slug=<?=urlencode($c['slug'])?>"><?=e($c['name'])?></a><?php endforeach;?></aside>
<div><div class="listing-top"><p><?=count($products)?> product<?=count($products)!==1?'s':''?> available</p></div><?php if($products):?><div class="product-grid"><?php foreach($products as $p):?><article class="product-card"><a class="product-image" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>"><?php if($p['image']):?><img src="<?=shopImageUrl($p['image'])?>" alt="<?=e($p['name'])?>"><?php else:?><div class="product-placeholder">✦</div><?php endif;?></a><div class="product-body"><div class="product-category"><?=e($p['category_name'])?></div><a class="product-name" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>"><?=e($p['name'])?></a><div class="product-price">From ₹<?=number_format((float)$p['starting_price'],2)?></div><div class="product-footer"><span class="product-unit"><?=number_format((int)$p['pack_count'])?> pack option<?=((int)$p['pack_count'])!==1?'s':''?></span><a class="add-btn" href="<?=BASE_URL?>product.php?slug=<?=urlencode($p['slug'])?>">View</a></div></div></article><?php endforeach;?></div><?php else:?><div class="empty-state"><h2>No products available</h2><p>Please check back soon.</p></div><?php endif;?></div></div></div></section>
<?php require 'includes/store-footer.php';?>
