<?php
declare(strict_types=1);
require_once '../../config/database.php';require_once '../../config/config.php';require_once '../../includes/functions.php';require_once '../../includes/auth.php';
requireAdmin();
$pageTitle='Inventory';$currentPage='inventory';
$search=trim($_GET['search']??'');$categoryId=filter_input(INPUT_GET,'category_id',FILTER_VALIDATE_INT);$status=$_GET['status']??'';
if(!in_array($status,['','in_stock','low_stock','out_of_stock'],true))$status='';
$categories=$pdo->query("SELECT id,name FROM categories WHERE status='active' ORDER BY display_order ASC,name ASC")->fetchAll(PDO::FETCH_ASSOC);
$sql="SELECT p.id AS product_id,p.name AS product_name,p.image,p.stock,p.low_stock_threshold,p.price,p.status AS product_status,c.name AS category_name,u.short_name AS unit_short_name,COUNT(CASE WHEN pv.status='active' THEN 1 END) AS pack_count FROM products p INNER JOIN categories c ON c.id=p.category_id LEFT JOIN units u ON u.id=p.unit_id LEFT JOIN product_variants pv ON pv.product_id=p.id";
$where=[];$params=[];
if($search!==''){$where[]="(p.name LIKE :search OR c.name LIKE :search)";$params[':search']='%'.$search.'%';}
if($categoryId){$where[]="p.category_id=:category_id";$params[':category_id']=$categoryId;}
if($status==='in_stock')$where[]="p.stock>p.low_stock_threshold";elseif($status==='low_stock')$where[]="p.stock>0 AND p.stock<=p.low_stock_threshold";elseif($status==='out_of_stock')$where[]="p.stock<=0";
if($where)$sql.=" WHERE ".implode(' AND ',$where);
$sql.=" GROUP BY p.id,p.name,p.image,p.stock,p.low_stock_threshold,p.price,p.status,c.name,u.short_name ORDER BY CASE WHEN p.stock<=0 THEN 1 WHEN p.stock<=p.low_stock_threshold THEN 2 ELSE 3 END,p.name ASC";
$s=$pdo->prepare($sql);$s->execute($params);$inventory=$s->fetchAll(PDO::FETCH_ASSOC);
$totalProducts=count($inventory);$inStockCount=$lowStockCount=$outOfStockCount=0;
foreach($inventory as $i){if((float)$i['stock']<=0)$outOfStockCount++;elseif((float)$i['stock']<=(float)$i['low_stock_threshold'])$lowStockCount++;else$inStockCount++;}
$success=$_SESSION['success']??null;$error=$_SESSION['error']??null;unset($_SESSION['success'],$_SESSION['error']);
function invQty(float $v):string{return rtrim(rtrim(number_format($v,3,'.',''),'0'),'.');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($pageTitle)?> | <?=e(SITE_NAME)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?=BASE_URL?>assets/css/admin.css"><style>.inventory-stat{background:#fff;border-radius:13px;padding:18px 20px;box-shadow:0 3px 18px rgba(0,0,0,.045);height:100%}.stat-value{color:#075B2A;font-size:25px;font-weight:700}.stock-badge{display:inline-flex;padding:5px 10px;border-radius:20px;font-size:11px;font-weight:600}.stock-in{background:#e6f5e8;color:#176b2d}.stock-low{background:#fff4d7;color:#936b00}.stock-out{background:#fde8e8;color:#b42318}.product-thumb{width:52px;height:52px;object-fit:cover;border-radius:10px}.product-placeholder{width:52px;height:52px;border-radius:10px;background:#edf5ea;color:#075B2A;display:flex;align-items:center;justify-content:center;font-weight:700}</style></head><body>
<?php require_once '../../includes/admin-sidebar.php';?><main class="admin-main"><?php require_once '../../includes/admin-header.php';?><div class="admin-content">
<div class="row g-4 mb-4"><?php foreach([['Total Products',$totalProducts],['In Stock',$inStockCount],['Low Stock',$lowStockCount],['Out of Stock',$outOfStockCount]] as $x):?><div class="col-12 col-md-3"><div class="inventory-stat"><div class="text-muted" style="font-size:12px"><?=$x[0]?></div><div class="stat-value"><?=number_format($x[1])?></div></div></div><?php endforeach;?></div>
<?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="admin-card"><div class="admin-card-header"><div><h5>Inventory</h5><div class="text-muted" style="font-size:11px;margin-top:3px;">One shared stock per product. Packs consume this stock according to their size.</div></div></div>
<div class="px-4 py-3 border-bottom"><form method="get"><div class="row g-2"><div class="col-12 col-md-5"><input class="form-control" name="search" value="<?=e($search)?>" placeholder="Search product or category..."></div><div class="col-12 col-md-3"><select class="form-select" name="category_id"><option value="">All Categories</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=$categoryId===$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-12 col-md-2"><select class="form-select" name="status"><option value="">All</option><option value="in_stock" <?=$status==='in_stock'?'selected':''?>>In Stock</option><option value="low_stock" <?=$status==='low_stock'?'selected':''?>>Low Stock</option><option value="out_of_stock" <?=$status==='out_of_stock'?'selected':''?>>Out of Stock</option></select></div><div class="col-6 col-md-1"><button class="btn btn-lfm w-100">Search</button></div><div class="col-6 col-md-1"><a href="index.php" class="btn btn-light border w-100">Clear</a></div></div></form></div>
<div class="admin-card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Product</th><th>Category</th><th>Base Price</th><th>Shared Stock</th><th>Packs</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>
<?php if(!$inventory):?><tr><td colspan="7" class="text-center py-5 text-muted">No inventory found.</td></tr><?php endif;?>
<?php foreach($inventory as $i):$stock=(float)$i['stock'];$threshold=(float)$i['low_stock_threshold'];$cls=$stock<=0?'stock-out':($stock<=$threshold?'stock-low':'stock-in');$label=$stock<=0?'Out of Stock':($stock<=$threshold?'Low Stock':'In Stock');?><tr><td><div class="d-flex align-items-center"><?php if($i['image']):?><img class="product-thumb" src="<?=BASE_URL.e($i['image'])?>" alt="<?=e($i['product_name'])?>"><?php else:?><div class="product-placeholder"><?=e(strtoupper(mb_substr($i['product_name'],0,1)))?></div><?php endif;?><div class="ms-3"><strong><?=e($i['product_name'])?></strong></div></div></td><td><?=e($i['category_name'])?></td><td>₹<?=number_format((float)$i['price'],2)?> / <?=e($i['unit_short_name']??'unit')?></td><td><strong><?=e(invQty($stock))?> <?=e($i['unit_short_name']??'')?></strong><div class="text-muted" style="font-size:10px">Alert at <?=e(invQty($threshold))?></div></td><td><?=number_format((int)$i['pack_count'])?></td><td><span class="stock-badge <?=$cls?>"><?=$label?></span></td><td class="text-end"><button class="btn btn-sm btn-lfm-light" data-bs-toggle="modal" data-bs-target="#adjustModal" data-product-id="<?=$i['product_id']?>" data-product-name="<?=e($i['product_name'])?>" data-stock="<?=e(invQty($stock))?>" data-unit="<?=e($i['unit_short_name']??'')?>">Adjust</button></td></tr><?php endforeach;?>
</tbody></table></div></div></div></div></main>
<div class="modal fade" id="adjustModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" action="inventory_action.php"><div class="modal-header"><h5 class="modal-title">Adjust Inventory</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="product_id" id="adjustProductId"><div class="mb-3"><strong id="adjustProductName"></strong><div class="text-muted" id="adjustCurrentStock"></div></div><label class="form-label">Adjustment</label><select name="adjustment_type" class="form-select mb-3"><option value="add">Add Stock</option><option value="remove">Remove Stock</option><option value="set">Set Stock</option></select><label class="form-label">Quantity</label><input type="number" name="quantity" class="form-control" min="0" step="0.001" required><label class="form-label mt-3">Reason</label><textarea name="reason" class="form-control" rows="3" maxlength="1000"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button class="btn btn-lfm">Save Stock</button></div></form></div></div></div>
<script>document.getElementById('adjustModal').addEventListener('show.bs.modal',e=>{const b=e.relatedTarget;document.getElementById('adjustProductId').value=b.dataset.productId;document.getElementById('adjustProductName').textContent=b.dataset.productName;document.getElementById('adjustCurrentStock').textContent='Current stock: '+b.dataset.stock+' '+b.dataset.unit;});</script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>
